# Generated by Django 3.2.4 on 2021-07-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_careerquestion_careerquestionanswer_careerquestionoption_course_savedcourse_savedscholarship_savedsc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerQuestionAnswer',
        ),
    ]
