# Generated by Django 3.2.4 on 2021-07-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_careerquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerquestionanswer',
            name='answer',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careerquestionanswer',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
