# Generated by Django 3.2.4 on 2021-07-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210705_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
            ],
        ),
    ]
