# Generated by Django 3.2.4 on 2021-07-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_savedschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedschool',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
