# Generated by Django 3.2.4 on 2021-07-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_studentaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
